#!/usr/bin/env bash

# shellcheck source=common.sh
source "$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)/common.sh"

load_promotion_environment() {
  local repo_root="${1:?repository root is required}"
  local names=(
    PROMOTION_UI_BASE_URL
    PROMOTION_API_BASE_URL
    PROMOTION_SOURCE_HOST_ID
    PROMOTION_SOURCE_HOST_LABEL
    PROMOTION_TARGET_HOST_ID
    PROMOTION_TARGET_HOST_LABEL
    PROMOTION_PLATFORM_MATCH
    PROMOTION_PIPELINE_MATCH
    PROMOTION_PIPELINE_VERSION
    PROMOTION_PRODUCT_ID
    PROMOTION_PRODUCT_VERSION
    PROMOTION_MINIMUM_MATCHING_ROWS
    PROMOTION_SELECTION_ENTITY_TYPE
    PROMOTION_SELECTION_ENTITY_LABEL
    PROMOTION_PROJECTION_TIMEOUT_MS
    PROMOTION_TEST_TIMEOUT_MS
    PROMOTION_EXPECT_TIMEOUT_MS
    PROMOTION_AUTH_STATE_FILE
    PROMOTION_REUSE_AUTH_STATE
    PROMOTION_API_PREFLIGHT
    PROMOTION_E2E_EMAIL
    PROMOTION_E2E_PASSWORD
    PROMOTION_E2E_USER_TYPE
  )
  local -A supplied=()
  local -A values=()
  local name

  for name in "${names[@]}"; do
    if [[ -v $name ]]; then
      supplied["$name"]=1
      values["$name"]="${!name}"
    fi
  done

  load_test_environment "$repo_root"

  for name in "${names[@]}"; do
    if [[ -n "${supplied[$name]:-}" ]]; then
      printf -v "$name" '%s' "${values[$name]}"
    fi
  done

  PROMOTION_UI_BASE_URL="${PROMOTION_UI_BASE_URL:-https://localhost:3000}"
  PROMOTION_API_BASE_URL="${PROMOTION_API_BASE_URL:-$PROMOTION_UI_BASE_URL}"
  PROMOTION_MINIMUM_MATCHING_ROWS="${PROMOTION_MINIMUM_MATCHING_ROWS:-11}"
  PROMOTION_SELECTION_ENTITY_TYPE="${PROMOTION_SELECTION_ENTITY_TYPE:-config}"
  PROMOTION_SELECTION_ENTITY_LABEL="${PROMOTION_SELECTION_ENTITY_LABEL:-Config}"
  PROMOTION_PROJECTION_TIMEOUT_MS="${PROMOTION_PROJECTION_TIMEOUT_MS:-120000}"
  PROMOTION_TEST_TIMEOUT_MS="${PROMOTION_TEST_TIMEOUT_MS:-180000}"
  PROMOTION_EXPECT_TIMEOUT_MS="${PROMOTION_EXPECT_TIMEOUT_MS:-30000}"
  PROMOTION_REUSE_AUTH_STATE="${PROMOTION_REUSE_AUTH_STATE:-false}"
  PROMOTION_API_PREFLIGHT="${PROMOTION_API_PREFLIGHT:-auto}"

  export PROMOTION_UI_BASE_URL PROMOTION_API_BASE_URL
  export PROMOTION_SOURCE_HOST_ID PROMOTION_SOURCE_HOST_LABEL
  export PROMOTION_TARGET_HOST_ID PROMOTION_TARGET_HOST_LABEL
  export PROMOTION_PLATFORM_MATCH PROMOTION_PIPELINE_MATCH PROMOTION_PIPELINE_VERSION
  export PROMOTION_PRODUCT_ID PROMOTION_PRODUCT_VERSION
  export PROMOTION_MINIMUM_MATCHING_ROWS PROMOTION_PROJECTION_TIMEOUT_MS
  export PROMOTION_SELECTION_ENTITY_TYPE PROMOTION_SELECTION_ENTITY_LABEL
  export PROMOTION_TEST_TIMEOUT_MS PROMOTION_EXPECT_TIMEOUT_MS
  export PROMOTION_AUTH_STATE_FILE PROMOTION_REUSE_AUTH_STATE
  export PROMOTION_API_PREFLIGHT
  export PROMOTION_E2E_EMAIL PROMOTION_E2E_PASSWORD PROMOTION_E2E_USER_TYPE
}

require_promotion_canary() {
  require_value PROMOTION_SOURCE_HOST_ID
  require_value PROMOTION_SOURCE_HOST_LABEL
  require_value PROMOTION_TARGET_HOST_ID
  require_value PROMOTION_TARGET_HOST_LABEL
  require_value PROMOTION_PLATFORM_MATCH
  require_value PROMOTION_PIPELINE_MATCH
  require_value PROMOTION_PIPELINE_VERSION
  require_value PROMOTION_PRODUCT_ID
  require_value PROMOTION_PRODUCT_VERSION

  if [[ "$PROMOTION_SOURCE_HOST_ID" == "$PROMOTION_TARGET_HOST_ID" ]]; then
    echo "PROMOTION_SOURCE_HOST_ID and PROMOTION_TARGET_HOST_ID must be different" >&2
    return 2
  fi
}

print_promotion_profile() {
  echo "promotionSource=$PROMOTION_SOURCE_HOST_LABEL promotionTarget=$PROMOTION_TARGET_HOST_LABEL ui=$PROMOTION_UI_BASE_URL"
}
